name: 🚫 Errore canale (Diretto)
description: Per i canali che mostrano l'errore "Errore canale (Diretto)".
title: "[ERRORE DIRETTO] "
labels:
  - Errore
  - Diretto
body:
  - type: markdown
    attributes:
      value: |
        Grazie per esserti preso del tempo per migliorare Zappr inviandoci questa segnalazione.

        **Ti consigliamo di non compilare tutto questo modulo manualmente.** Se sei su questa pagina dopo aver cliccato "New issue", ti consigliamo invece di cliccare il pulsante "Segnala tramite GitHub" nella finestra. Così facendo, la maggior parte del modulo verrà compilata automaticamente.

        **Prima di inviare questa issue, però,** controlla che nessun altro abbia già segnalato lo stesso problema. [Vai sulla scheda Issues](https://github.com/ZapprTV/channels/issues?q=is%3Aissue+is%3Aopen+label%3AErrore+label%3ADiretto) e cerca il nome del canale che vuoi segnalare: se non trovi una issue con il tuo stesso problema, continua a compilare questo modulo.

        **Inoltre, ti ricordiamo che questo form è solo per i canali che mostrano una finestra d'errore ("Errore canale"). Se il canale che vuoi segnalare dà problemi ma non dà errore ed è visibile, questo è il form sbagliato.**
  - type: input
    id: name
    attributes:
      label: Nome contenuto
      placeholder: LA7
    validations:
      required: true
  - type: input
    id: lcn
    attributes:
      label: Numerazione contenuto
      description: |
        Una delle numerazioni del contenuto. Se c'è più volte nella lista dei canali ne va bene una qualsiasi di quelle presenti.
      placeholder: "7"
    validations:
      required: true
  - type: input
    id: info
    attributes:
      label: URL canale
    validations:
      required: true
  - type: dropdown
    id: zappr
    attributes:
      label: Il contenuto è visibile correttamente da altre parti?
      description: |
        Cerca altri modi di guardare il contenuto in streaming e dicci se dà errore solo su Zappr o no. Se è visible tramite HbbTV e hai una TV/decoder abilitato all'HbbTV, ti consigliamo di provare con quello.
      options:
        - No, succede anche da altre parti
        - Sì, succede solo su Zappr
        - Il contenuto è solo su Zappr / Non l'ho trovato da altre parti
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Su che browser avviene?
      description: |
        Se possibile, prova a testare il canale con più browser possibili, per vedere se il problema è il browser.
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Brave
        - Altro
    validations:
      required: true