name: Genera documentazione schema
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "schema.json"
  pull_request:
    paths:
      - "schema.json"

jobs:
  documentation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Installa Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Genera documentazione
        shell: bash
        working-directory: ./
        run: |
          npm i json-schema-static-docs
          npx json-schema-static-docs -i . -o .

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Genera documentazione schema"
          file_pattern: "schema.md"